#spring:
#  datasource:
#    url: jdbc:mysql://192.168.10.225:3306/activity?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
#    username: ld225_rw
#    password: laidian225
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect

job:
  token: 123456

server:
  servlet:
    context-path: /
  port: 8081
  address: 0.0.0.0


logging:
  level:
    root: info